# Site settings
name: Sahil Yadav
email: sahil16263@iiitd.ac.in
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Python, Java, Springboot, Machine Learning, Deep Learning, Startups, Devops, docker, aws, html, css, react, nodejs, node"
skills: "Associate Software Developer Engineer in New Delhi, India"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sahil-yadav-a1aa31136/
  - title: medium
    url: https://medium.com/@sahil16263
  - title: twitter
    url: https://twitter.com/sahil_yadav96
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: eeaf44
  primary-rgb: "0, 0, 0"
  secondary: 000000
  secondary-dark: 000000
  section-tout: eeaf44



# Build settings
markdown: kramdown
permalink: pretty
