# Site settings
name: Sahil Yadav
email: sahil16263@iiitd.ac.in
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Python, Java, Springboot, Machine Learning, Deep Learning, Startups, Devops, docker, aws, html, css, react, nodejs, node,Engineering,Design,Technical,Programming,Product,Software,Software Engineering,Software Development,Optimizing Code,Optimizing,Code,Strategic Direction,Distributed Computing,Information Retrieval,Architectures,Github,git,mongo, sql, back end, api, developer tools, kafka, REST, salesforce,DevOps, Machine Learning ,Data Mining,Website Development, Blockchain ,Android Development and IOT, Agile,JavaScript , JQuery , MATLAB, C++, YAML, SQL, PHP,
Scene Builder, Android Studio, ML, scikit-learn, Tensorflow, Django, Node, Scripting, LaTex, nginx, scrum, MVC, Systems Management ,Iot, Algorithm Design and Analysis, WebApp Development, Machine Learning, Continuous Integration and Deployment"
skills: "Associate Software Developer Engineer in New Delhi, India"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: github
    url: https://github.com/sahilyadav-here
  - title: linkedin
    url: https://www.linkedin.com/in/sahil-yadav-a1aa31136/
  - title: twitter
    url: https://twitter.com/sahil_yadav96
    
# Google webmaster tools
google_verify: ywYKvGarjvJbMTvlKVPv8eLmpn0hC0Rlghx4D1FGjB0

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0F0F0F
  primary-rgb: "0, 0, 0"
  secondary: 0F0F0F
  secondary-dark: 0F0F0F
  section-tout: eeaf44



# Build settings
markdown: kramdown
permalink: pretty
